version: '3.8'
services:
   mongodb:
      image: mongo:4.4.4-bionic
      container_name: dit192-db
      hostname: mongo
      restart: "always"
      entrypoint: ["/usr/bin/mongod","--bind_ip_all"]
      ports:
         - "${MONGO_PORT}:27017"
      volumes:
         - dit192_data:/data/db/

   mongoseed:
      build: .
      container_name: dit192-seed
      depends_on:
         - mongodb
      restart: "no"
      profiles: ["init"]
      entrypoint: ["bash", "-c", "sleep 10 && mongoimport --host mongo:27017 --db ${MONGO_DATABASE} --collection attractions --drop --file /docker-entrypoint-initdb.d/attractions.json --jsonArray && mongoimport --host mongo:27017 --db ${MONGO_DATABASE} --collection restaurants --drop --file /docker-entrypoint-initdb.d/restaurants.json --jsonArray && mongoimport --host mongo:27017 --db ${MONGO_DATABASE} --collection games --drop --file /docker-entrypoint-initdb.d/games.json --jsonArray"]

volumes:
   dit192_data:
