version: '3.8'
services: 
   mongodb:
      image: mongo:4.4.4-bionic
      container_name: dit192-db
      hostname: dit192-db
      restart: always
      ports:
         - "${MONGO_PORT}:27017"
      volumes:
         - dit192_data:/data/db/
volumes:
   dit192_data: