version: '3.8'
services: 
   mongodb:
      image: mongo:4.4.4-bionic
      container_name: dit192-db
      hostname: dit192-db
      restart: always
      env_file:
         - mongodb.env
      ports: 
         - 27017:27017
      volumes:
         - ./.docker/mongodb/home:/home/mongodb
         - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
         - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
         - ./.docker/mongodb/data/db/:/data/db/
         - ./.docker/mongodb/data/log/:/var/log/mongodb/
      command: ["-f", "/etc/mongod.conf"]
